Lesson02_MbmStore_startup/MbmStore/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MbmStore.Models
{
    public class Invoice
    {
        // fields
        private decimal totalPrice;


        // properties
        public int InvoiceId
        {
            get; set;
        }

        public DateTime OrderDate
        {
            get; set;
        }

        public decimal TotalPrice
        {
            get;
        }

        public Customer Customer
        {
            get; set;
        }

        public List<OrderItem> OrderItems
        {
            get; set;
        } = new List<OrderItem>();



        // constructors

        public Invoice(int invoiceId, DateTime orderDate, Customer customer)
        {
            InvoiceId = invoiceId;
            OrderDate = orderDate;
            Customer = customer;
        }

        public void AddOrderItem(Product product, int quantity)
        {
            OrderItems.Add(new OrderItem(product, quantity));
        }
    }
}

Lesson02_MbmStore_startup/MbmStore/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MbmStore.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MbmStore.Controllers
{
    public class InvoiceController : Controller
    {

        [HttpPost]
        public IActionResult Index(int? customer)
        {
            List<SelectListItem> customers = new List<SelectListItem>();
            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();



            foreach (Invoice invoice in Repository.Invoices)
            {

               


                if (invoice.Customer.CustomerId == customer )
                {
                    customers.Add(new SelectListItem
                    {

                        Text = invoice.Customer.Firstname + "" +
                  invoice.Customer.Lastname,
                        Value = invoice.Customer.CustomerId.ToString(),
                        Selected = true



                    });

                }

                else
                {
                    customers.Add(new SelectListItem
                    {

                        Text = invoice.Customer.Firstname + "" +
             invoice.Customer.Lastname,
                        Value = invoice.Customer.CustomerId.ToString(),
                        



                    });

                }


            }

          

            ViewData["Customers"] = customers;



            ViewBag.Invoices = Repository.Invoices.Where(r => r.Customer.CustomerId == customer).ToList(); ;
            return View();
        }


        public IActionResult Index()
        {

        

            List<SelectListItem> customers = new List<SelectListItem>();
            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();

            foreach (Invoice invoice in Repository.Invoices )
            {


                customers.Add(new SelectListItem
                {
                   
                Text = invoice.Customer.Firstname + "" +
                    invoice.Customer.Lastname,
                    Value = invoice.Customer.CustomerId.ToString()


                    

            });
            }

            ViewData["Customers"] = customers;

            ViewBag.Invoices = Repository.Invoices;
            return View();
        }
    }
}

Lesson02_MbmStore_startup/MbmStore/Views/Invoice/index.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@using System.Collections.Generic;
@using MbmStore.Models
@{
    //Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "index";
}

<style>
    table {
        display: table;
        border-collapse: separate;
        border-spacing: 15px;
        border-color: gray;
    }
</style>

<h2>Invoices</h2>
<form method="post" asp-controller="Invoice" asp-action="index">
    <div>
        <select name="customer" id="customer" asp-items="@ViewData["Customers"] as List<SelectListItem>">
        </select>
        <button type="submit">Show invoices</button>
    </div>

    <div>

        @foreach (Invoice invoice in ViewBag.Invoices)
        {


            decimal price = 0M;


            <table>

                <tr>
                    <th>Customer</th>
                    <th>Product 1</th>
                    <th>Product 2</th>
                    <th>Product Price 1</th>
                    <th>Product Price 2</th>
                    <th>Price Total</th>
                    <th></th>
                </tr>
                <tr>
                    <td>@invoice.Customer.Firstname @invoice.Customer.Lastname</td>

                    @foreach (OrderItem product in invoice.OrderItems)
                    {
                        <td>@product.Product.Title</td>



                    }




                    @foreach (OrderItem product in invoice.OrderItems)
                    {
                        <td> @String.Format("{0:0.00}", product.Product.Price)</td>
                        price += product.Product.Price;
                    }

                    <td>
                        @String.Format("{0:0.00}", price)
                    </td>



                </tr>
            </table>

        }


    </div>





</form>




